language: php

branches:
  only:
    - master

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - nightly

before_install:
  - source .travis/xdebug.sh
  - xdebug-disable

script:
  - cd $TRAVIS_BUILD_DIR
  - ./run-phpunit.sh --user travis --database wordpress_test --password "" --create-database
