language: php

branches:
  only:
    - master

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - nightly

script:
  - cd $TRAVIS_BUILD_DIR
  - ./run-phpunit.sh --user travis --database wordpress_test --password "" --create-database --no-run-php-cs

after_success:
    - bash <(curl -s https://codecov.io/bash)
