language: php

branches:
  only:
    - master

php:
  - 7.0
  - 7.1
  - nightly

env:
  - WP_VERSION=latest WP_MULTISITE=0

script:
  - cd $TRAVIS_BUILD_DIR
  - ./run-phpunit.sh --user travis --database wordpress_test --password ""
